TERMUX_PKG_HOMEPAGE=https://github/djunekz/termux-app-store
TERMUX_PKG_DESCRIPTION="The ultimate OSINT framework"
TERMUX_PKG_LICENSE="MIT"
TERMUX_PKG_MAINTAINER="@termux-app-store"
TERMUX_PKG_VERSION=1.2.0
TERMUX_PKG_SRCURL=https://github.com/djunekz/archive/releases/download/v${TERMUX_PKG_VERSION}/zora
TERMUX_PKG_SHA256=67a14fda2deb84d22c9a9129a9707ed21bad6d25ac2de884c4ed888e6ba197cc
TERMUX_PKG_DEPENDS="python"
TERMUX_PKG_BUILD_IN_SRC=true
